spring.application.name=webtechjs

spring.datasource.url=jdbc:postgresql://dpg-d8ek5fm8bjmc73b6sl2g-a.oregon-postgres.render.com:5432/filmapp_db

spring.datasource.username=filmapp_db_user

spring.datasource.password=MoRia88DvsDgmZrQoGIR2uwc9PddyOtE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081